/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/styles /IndexStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles /LoginPStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles /RegisterPStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles /LoginDStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles /RegisterDStyles`; params?: Router.UnknownInputParams; } | { pathname: `/passenger/LoginP`; params?: Router.UnknownInputParams; } | { pathname: `/passenger/RegisterP`; params?: Router.UnknownInputParams; } | { pathname: `/driver/LoginD`; params?: Router.UnknownInputParams; } | { pathname: `/driver/RegisterD`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/styles /IndexStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles /LoginPStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles /RegisterPStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles /LoginDStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles /RegisterDStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/passenger/LoginP`; params?: Router.UnknownOutputParams; } | { pathname: `/passenger/RegisterP`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/LoginD`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/RegisterD`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/styles /IndexStyles${`?${string}` | `#${string}` | ''}` | `/styles /LoginPStyles${`?${string}` | `#${string}` | ''}` | `/styles /RegisterPStyles${`?${string}` | `#${string}` | ''}` | `/styles /LoginDStyles${`?${string}` | `#${string}` | ''}` | `/styles /RegisterDStyles${`?${string}` | `#${string}` | ''}` | `/passenger/LoginP${`?${string}` | `#${string}` | ''}` | `/passenger/RegisterP${`?${string}` | `#${string}` | ''}` | `/driver/LoginD${`?${string}` | `#${string}` | ''}` | `/driver/RegisterD${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/styles /IndexStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles /LoginPStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles /RegisterPStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles /LoginDStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles /RegisterDStyles`; params?: Router.UnknownInputParams; } | { pathname: `/passenger/LoginP`; params?: Router.UnknownInputParams; } | { pathname: `/passenger/RegisterP`; params?: Router.UnknownInputParams; } | { pathname: `/driver/LoginD`; params?: Router.UnknownInputParams; } | { pathname: `/driver/RegisterD`; params?: Router.UnknownInputParams; };
    }
  }
}
